// User & Admin
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
  BLOCKED = 'BLOCKED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum AdminStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

// Category & Product
export enum CategoryStatus {
  ACTIVE = 'ACTIVE',
  HIDDEN = 'HIDDEN',
  DISABLED = 'DISABLED',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  HIDDEN = 'HIDDEN',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISABLED = 'DISABLED',
  ARCHIVED = 'ARCHIVED',
}

export enum DeliveryType {
  PRELOADED_ACCOUNT = 'PRELOADED_ACCOUNT',
  LICENSE_KEY = 'LICENSE_KEY',
  ACTIVATION_LINK = 'ACTIVATION_LINK',
  REDEEM_CODE = 'REDEEM_CODE',
  TEXT_SECRET = 'TEXT_SECRET',
  FILE_DOWNLOAD = 'FILE_DOWNLOAD',
  MANUAL_DELIVERY = 'MANUAL_DELIVERY',
  API_FULFILMENT = 'API_FULFILMENT',
  SUPPLIER_FULFILMENT = 'SUPPLIER_FULFILMENT',
  CUSTOM = 'CUSTOM',
}

export enum DeliverySpeed {
  INSTANT = 'INSTANT',
  MANUAL = 'MANUAL',
}

// Inventory
export enum InventoryStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  DISABLED = 'DISABLED',
  EXPIRED = 'EXPIRED',
  REPLACED = 'REPLACED',
  RETURNED = 'RETURNED',
  ERROR = 'ERROR',
}

// Wallet & Ledger
export enum WalletTxType {
  DEPOSIT = 'DEPOSIT',
  ORDER_PURCHASE = 'ORDER_PURCHASE',
  REFUND = 'REFUND',
  REFERRAL_COMMISSION = 'REFERRAL_COMMISSION',
  PROMOTIONAL_CREDIT = 'PROMOTIONAL_CREDIT',
  ADMIN_CREDIT = 'ADMIN_CREDIT',
  ADMIN_DEBIT = 'ADMIN_DEBIT',
  CHARGEBACK = 'CHARGEBACK',
  REVERSAL = 'REVERSAL',
}

export enum TxDirection {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum TxStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

// Deposits
export enum DepositStatus {
  AWAITING_TXID = 'AWAITING_TXID',
  VERIFYING = 'VERIFYING',
  PENDING_CONFIRMATIONS = 'PENDING_CONFIRMATIONS',
  CONFIRMED = 'CONFIRMED',
  CREDITED = 'CREDITED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  DUPLICATE = 'DUPLICATE',
  EXPIRED = 'EXPIRED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

// Orders & Deliveries
export enum OrderStatus {
  PENDING = 'PENDING',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PROCESSING = 'PROCESSING',
  FULFILLED = 'FULFILLED',
  PARTIALLY_FULFILLED = 'PARTIALLY_FULFILLED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  DELIVERED = 'DELIVERED',
  VIEWED = 'VIEWED',
  FAILED = 'FAILED',
}

export enum RefundType {
  FULL_REFUND = 'FULL_REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  WALLET_CREDIT = 'WALLET_CREDIT',
  REPLACEMENT = 'REPLACEMENT',
}

// Warranty & Support
export enum WarrantyStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NEED_CUSTOMER_INFO = 'NEED_CUSTOMER_INFO',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REPLACED = 'REPLACED',
  REFUNDED = 'REFUNDED',
  CLOSED = 'CLOSED',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  WAITING_ADMIN = 'WAITING_ADMIN',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum MessageSenderType {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

// Broadcasts
export enum BroadcastStatus {
  DRAFT = 'DRAFT',
  QUEUED = 'QUEUED',
  SENDING = 'SENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum BroadcastDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  BLOCKED = 'BLOCKED',
}
